name: test

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: gleam-lang/setup-erlang@v1.1.0
        with:
          otp-version: 22.1
      - uses: gleam-lang/setup-gleam@v1.0.2
        with:
          gleam-version: 0.13.2
      - run: rebar3 install_deps
      - run: cd _build/default/plugins/gleam_otp; curl https://raw.githubusercontent.com/gleam-lang/otp/main/gleam.toml -o gleam.toml; rebar3 compile
      - run: rebar3 eunit
      - run: DEBUG=1 rebar3 shine
      - run: gleam format --check src test
